### PR TITLE
Bump turbine version tp 0.5.0

### PR DESCRIPTION
**Pull request by anna-cross**

### CODE REVIEW

**Review by jayjayjpg — APPROVED** [review]
:sparkles:

**Comment by jmar910** [comment]
@anna-cross give this a rebase and also make sure to update https://github.com/meroxa/turbine-js/blob/master/templates/javascript/package.json#L6 with the new version number as well

**Review by jmar910 — CHANGES_REQUESTED** [review]
see comment

**Review by jmar910 — APPROVED** [review]
🎉

**Comment by jmar910** [comment]
@anna-cross good to merge! This will auto publish 0.5.0 to the npm registry after merge. 

Just a heads up, you will have to make a cli change here https://github.com/meroxa/cli/blob/master/cmd/meroxa/turbine_cli/utils.go#L23 to tell the CLI to use the new published version. Ideally the version update in CLI would happen alongside whatever breaking changes are made to the CLI, otherwise it could put the meroxa CLI in a bad state where it is trying to use new APIs that dont exist in the older version of turbine-js.

**Comment by anna-cross** [comment]
> @anna-cross good to merge! This will auto publish 0.5.0 to the npm registry after merge.
> 
> Just a heads up, you will have to make a cli change here https://github.com/meroxa/cli/blob/master/cmd/meroxa/turbine_cli/utils.go#L23 after publish to tell the CLI to use the new published version. Ideally the version update in CLI would happen alongside whatever breaking changes are made to the CLI, otherwise it could put the meroxa CLI in a bad state where it is trying to use new APIs that dont exist in the older version of turbine-js.

Gotcha! Thanks for pointing it out! I created a PR on cli to bump the version to match :) https://github.com/meroxa/cli/pull/416

**Pull request merged**
